#!/usr/bin/env python
from PIL import Image
import sys

def convert(filename):
    image = Image.open(filename).convert("1")
    width, height = image.size

    data = list(image.getdata())

    # PF0.4-7 PF1.7-0 PF2.0-7

    # PF0
    pf0 = []
    for y in range(height):
        byte = 0
        for x in range(4):
            if data[y * width + x]:
                byte |= 0x10 << x
        pf0.append(byte)

    # PF1
    pf1 = []
    for y in range(height):
        byte = 0
        for x in range(8):
            if data[y * width + 4 + 7 - x]:
                byte |= 0x1 << x
        pf1.append(byte)

    # PF2
    pf2 = []
    for y in range(height):
        byte = 0
        for x in range(8):
            if data[y * width + 12 + x]:
                byte |= 0x1 << x
        pf2.append(byte)

    for name, table in [('pf0', pf0), ('pf1', pf1), ('pf2', pf2)]:
        print '%s_%s:' % (filename.rsplit('.', 1)[0], name)
        print '.byte %s' % ','.join([str(x) for x in table])

for arg in sys.argv[1:]:
    convert(arg)
